service: apigatewayproject

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - ses:*
      Resource: '*'

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  tableName: player-points
  s3Sync:
    - bucketName: myserverlessdemoproject-2211
      localDir: uploadData

functions:
  getUser:
    handler: lambdas/endpoints/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: get
          CORS: true
  getPlayerScore:
    handler: lambdas/endpoints/getPlayerScore.handler
    events:
      - http:
          path: get-player-score/{ID}
          method: get
          CORS: true
  setPlayerScore:
    handler: lambdas/endpoints/setPlayerScore.handler
    events:
      - http:
          path: set-player-score/{ID}
          method: post
          CORS: true
  sendEmail:
    handler: lambdas/endpoints/sendEmail.handler
    events:
      - http:
          path: send-email
          method: post
          CORS: true
  updatePlayerScore:
    handler: lambdas/endpoints/updatePlayerScore.handler
    events:
      - http:
          path: update-player-score/{ID}
          method: post
          CORS: true
  pickUsingQuery:
    handler: lambdas/endpoints/pickUsingQuery.handler
    events:
      - http:
          path: query-player-data/{batsman}
          method: post
          CORS: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myserverlessdemoproject-2211
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: batsman
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: batsman-index
            KeySchema:
                - AttributeName: batsman
                  KeyType: HASH
            Projection:
                ProjectionType: ALL
    
      

